#:schema node_modules/wrangler/config-schema.json

name = "langchain-js-cloudflare-prompt-tracing"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[vars]
PANGEA_DOMAIN = "aws.us.pangea.cloud"
